    define(
        function () {
            return {
                BridgeFeatureResults: [
                    { title: 'Bridge Name', data: 'BridgeName'},
                    { title: 'CDS', data: 'RouteId'},
                    { title: 'Route Name', data: 'RouteName'},
                    { title: 'NHS Class', data: 'NHSClass'},
                    { title: 'Lanes', data: 'NumberOfLanes'},
                    { title: 'Geographic Area', data: 'Jurisdiction'},
                    { title: 'Status', data: 'Status'},
                    { title: 'Centerline Miles', data: 'Length', format: '0,000.0000'},
                    { title: 'Lane Miles', data: 'LaneMiles', format: '0,000.0000'},
                    { title: 'Deck Area', data: 'deckarea', format: '0,000.0000'},
                    { title: 'AADT', data: 'AADT', format: '0,000.0000'},
                    { title: 'AADT Summary', data: 'aadtbin', format: '0,000.0000'},
                    { title: 'Super Structure Condition', data: 'SuperStructure'},
                    { title: 'Super Structure Summary', data: 'superstructurebin'},
                    { title: 'Sub Structure Condition', data: 'SubStructure'},
                    { title: 'Sub Structure Summary', data: 'substructurebin'},
                    { title: 'Deck Condition', data: 'DeckCond'},
                    { title: 'Deck Summary', data: 'deckbin'},
                    { title: 'Minimum Condition Summary', data: 'Minimum Condition Summary'},
                    { title: 'Minimum Condition', data: 'Minimum Condition'},
                ],

                RouteFeatureResults: [
                    { title: 'CDS', data: 'RouteId'},
                    { title: 'Route Name', data: 'RouteName'},
                    { title: 'NHS Class', data: 'NHSClass'},
                    { title: 'Lanes', data: 'NumberOfLanes'},
                    { title: 'Geographic Area', data: 'Jurisdiction'},
                    { title: 'PSR', data: 'PSR'},
                    { title: 'PSR Summary', data: 'PSRSummary'},
                    { title: 'Mean IRI', data: 'MeanIRI'},
                    { title: 'Roughness Summary', data: 'Roughness Summary'},
                    { title: 'Rut Depth', data: 'FullRUT'},
                    { title: 'Rut Summary', data: 'RUTSummary'},
                    { title: 'Centerline Miles', data: 'Length', format: '0,000.0000'},
                    { title: 'Lane Miles', data: 'LaneMiles', format: '0,000.0000'},
                    { title: 'Mitigation Present', data: 'MitigationPresent'},
                    { title: 'Risk Score', data: 'RiskScore'},
                    { title: 'Total Score', data: 'TotalScore'},
                    { title: 'AADT', data: 'AADT', format: '0,000.0000'},
                    { title: 'AADT Summary', data: 'aadtbin', format: '0,000.0000'},
                ],

                UnstableSlopeFeatureResults: [
                    { title: 'Route Name', data: 'RouteName'},
                    { title: 'NHS Class', data: 'NHSClass'},
                    { title: 'Lanes', data: 'NumberOfLanes'},
                    { title: 'Geographic Area', data: 'Jurisdiction'},
                    { title: 'PSR Summary', data: 'PSRSummary'},
                    { title: 'Mitigation Present', data: 'MitigationPresent'},
                    { title: 'Risk Score', data: 'RiskScore'},
                    { title: 'Risk Summary', data: 'riskbucket'},
                    { title: 'Hazard Score', data: 'HazardScore'},
                    { title: 'Hazard Summary', data: 'hazardscorebin'},
                    { title: 'Total Score', data: 'TotalScore'},
                    { title: 'Total Summary', data: 'totalscorebucket'},
                ],

                ProjectFeatureResults: [
                    { title: 'Geographic Area', data: 'Jurisdiction'},
                    { title: 'Program', data: 'Program'},
                    { title: 'Primary Work Category', data: 'PrimWorkCategory'},
                    { title: 'PDO Crashes', data: 'PDOCrashes'},
                    { title: 'Minor Crashes', data: 'MinorCrashes'},
                    { title: 'Major Crashes', data: 'MajorCrashes'},
                    { title: 'Fatal Crashes', data: 'FatalCrashes'},
                    { title: 'Total Crashes', data: 'TotalCrashes'},
                    { title: 'Major and Fatal Crash Summary', data: 'Major and Fatal Crash Summary'},
                    { title: 'Major and Fatal Crashes per 100M VMT', data: 'Major and Fatal Crashes per 100M VMT'},
                ]
            }
        });
